"""test

Revision ID: 08a5c42be6af
Revises: 7d5eacd852a8
Create Date: 2023-03-30 16:38:09.885414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a5c42be6af'
down_revision = '7d5eacd852a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groupid', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('groupname', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('adminname', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('groupid', name='users_groupid_key'),
    sa.UniqueConstraint('mobile', name='users_mobile_key')
    )
    # ### end Alembic commands ###
