"""users changes

Revision ID: 2b07ee843722
Revises: 7b49116dafbe
Create Date: 2023-03-30 17:38:49.405333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b07ee843722'
down_revision = '7b49116dafbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('userid', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'Users', ['userid'])
    op.drop_column('Users', 'confirmpass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('confirmpass', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'userid')
    # ### end Alembic commands ###
