"""added code column

Revision ID: 445a108e2aa5
Revises: 2b07ee843722
Create Date: 2023-03-31 11:08:55.481978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445a108e2aa5'
down_revision = '2b07ee843722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('code', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'code')
    # ### end Alembic commands ###
