"""changed group columns

Revision ID: 5a57222b792d
Revises: 445a108e2aa5
Create Date: 2023-04-05 13:29:20.121940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a57222b792d'
down_revision = '445a108e2aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.String(length=200), nullable=False),
    sa.Column('adminid', sa.String(length=200), nullable=False),
    sa.Column('groupname', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adminid'),
    sa.UniqueConstraint('groupid')
    )
    op.drop_table('Registergroup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Registergroup',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Registergroup_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('groupid', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('groupname', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('adminname', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('confirmpass', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Registergroup_pkey'),
    sa.UniqueConstraint('groupid', name='Registergroup_groupid_key'),
    sa.UniqueConstraint('mobile', name='Registergroup_mobile_key')
    )
    op.drop_table('Group')
    # ### end Alembic commands ###
