"""changes on role column

Revision ID: 6a3debe48d38
Revises: 85fc93879b81
Create Date: 2023-04-14 17:40:21.691403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a3debe48d38'
down_revision = '85fc93879b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Newwindow')
    op.drop_column('Users', 'groupid')
    op.drop_column('Users', 'windowid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('windowid', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('groupid', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_table('Newwindow',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Newwindow_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('windowid', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('startdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payamount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receivingpeople', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('durationOne', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durationTwo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('windowname', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Newwindow_pkey'),
    sa.UniqueConstraint('windowid', name='Newwindow_windowid_key')
    )
    # ### end Alembic commands ###
