"""added role & total group members columns

Revision ID: 712c149a8b8b
Revises: 5a57222b792d
Create Date: 2023-04-05 16:48:11.598574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712c149a8b8b'
down_revision = '5a57222b792d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('totalmembers', sa.String(length=200), nullable=False))
    op.add_column('Users', sa.Column('role', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'role')
    op.drop_column('Group', 'totalmembers')
    # ### end Alembic commands ###
