"""users table

Revision ID: 7d5eacd852a8
Revises: 
Create Date: 2023-03-30 08:05:24.597442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5eacd852a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.String(length=200), nullable=False),
    sa.Column('groupname', sa.String(length=200), nullable=False),
    sa.Column('adminname', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupid'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
