"""updated user column with windowid

Revision ID: a07ae7efa7ef
Revises: 297b61198e07
Create Date: 2023-04-16 11:52:58.666420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ae7efa7ef'
down_revision = '297b61198e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('windowid', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'windowid')
    # ### end Alembic commands ###
