"""added groupid column to Newwindow

Revision ID: a2200abe9a85
Revises: 4b7a7e366a91
Create Date: 2023-06-27 11:50:00.797970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2200abe9a85'
down_revision = '4b7a7e366a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Newwindow', sa.Column('groupid', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Newwindow', 'groupid')
    # ### end Alembic commands ###
